# Custom Domain Routing
# api_host MUST be <= 20 bytes
# auth_host MUST be <= 18 bytes
server:
  api_host: "arc-api.nekitori17.com"
  auth_host: "ar-au.nekitori17.com"

# Custom Package Name (Optional)
# Change the APK package name to install alongside the original app
package_name: "moe.low.arc.custom"

# Custom Signing Configuration
# If the keystore does not exist, a debug keystore will be generated automatically.
signing:
  keystore: "debug.keystore"
  alias: "androiddebugkey"
  keystore_password: "android"
  key_password: "android"