# Custom Domain Routing
# api_host MUST be <= 20 bytes
# auth_host MUST be <= 18 bytes
server:
  api_host: "arc-api.nekitori.com"
  auth_host: "au-v2.nekitori.com"

# Custom Signing Configuration
# If the keystore does not exist, a debug keystore will be generated automatically.
signing:
  keystore: "debug.keystore"
  alias: "androiddebugkey"
  keystore_password: "android"
  key_password: "android"